parent=keycloak.v2
darkMode=false
contentHashPattern=assets/.*
styles=css/light.css
scripts=js/light.js
title=Keycloak Administration Console
description=Light administration console for Keycloak 26.4.5
