parent=keycloak.v3
import=common/light
deprecatedMode=false
darkMode=false
contentHashPattern=assets/.*
styles=css/light.css
scripts=js/light.js
title=Account Management
description=Light account console for Keycloak 26.4.5
